micronaut:
  application:
    name: core-service
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: JWT@cthivE0lahragA1ndonesiAJWT@cthivE0lahragA1ndonesiA
  server:
    port: 8080
datasources:
  default:
    url: jdbc:postgresql://acthive-do-user-9317815-0.b.db.ondigitalocean.com:25060/acthive
    driverClassName: org.postgresql.Driver
    username: doadmin
    password: lfujgm37tl385bkn
    schema-generate: NONE
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages:
        - 'id.acthive.dao'
    properties:
      hibernate:
        show_sql: true